-- AeroApply PostgreSQL schema exported from the Floot project on 2026-09-01.
-- Current source database contains 0 data rows. This file preserves the live schema.

CREATE TABLE IF NOT EXISTS jobs (
  id text NOT NULL,
  canonical_url text NOT NULL UNIQUE,
  title text NOT NULL,
  company text NOT NULL,
  location text,
  score integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'discovered',
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS applications (
  id text NOT NULL,
  job_id text NOT NULL REFERENCES jobs(id),
  status text NOT NULL DEFAULT 'queued',
  resume_variant text,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS agent_runs (
  id text NOT NULL,
  job_id text NOT NULL REFERENCES jobs(id),
  agent text NOT NULL,
  status text NOT NULL,
  input jsonb NOT NULL DEFAULT '{}'::jsonb,
  output jsonb NOT NULL DEFAULT '{}'::jsonb,
  decision text,
  error text,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id text REFERENCES jobs(id),
  agent text,
  action text,
  status text NOT NULL,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS human_interventions (
  id text NOT NULL,
  job_id text NOT NULL REFERENCES jobs(id),
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS applications_job_id_idx ON applications(job_id);
CREATE INDEX IF NOT EXISTS agent_runs_job_id_idx ON agent_runs(job_id);
CREATE INDEX IF NOT EXISTS audit_events_job_id_idx ON audit_events(job_id);
CREATE INDEX IF NOT EXISTS human_interventions_job_id_idx ON human_interventions(job_id);
